Example 5 - Creating your own API/config/routes.rb
Rails.application.routes.draw do
	root "students#index"
  resources :students
  resources :instructors
  resources :courses
  resources :enrollments

end

Example 5 - Creating your own API/app/models/course.rb
class Course < ActiveRecord::Base

	validates :name, presence: true

	has_many :enrollments
	has_many :students, through: :enrollments
end

Example 5 - Creating your own API/app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
	belongs_to :student
	belongs_to :course
end

Example 5 - Creating your own API/app/models/instructor.rb
class Instructor < ActiveRecord::Base

	validates :name, presence: true
	has_many :students
end

Example 5 - Creating your own API/app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :instructor

	validates :name, presence: true
	belongs_to :instructor
	has_many :enrollments
	has_many :courses, :through => :enrollments

end

Example 5 - Creating your own API/app/controllers/courses_controller.rb
class CoursesController < ApplicationController

 before_action :set_course, only: [:show, :update, :destroy]
  respond_to :json

  def index
    respond_with Course.all
  end

  def create
    respond_with Course.create(book_params)
  end

  def show
    respond_with @course
  end

  def update
    respond_with @course.update(course_params)
  end

  def destroy
    respond_with @course.destroy
  end

  private
  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name)
  end

end

Example 5 - Creating your own API/app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController

  before_action :set_enrollment, only: [:show, :update, :destroy]
  respond_to :json, :html

  def index
    # respond_with enrollment: Enrollment.all, instructor_name: @instructor_name
    @enrollment = Enrollment.all
    respond_with @enrollment.to_json(
      :include => [
        { :student => {:only => :name} },
        { :course => { :only => :name } }
        ])
  end

  def create
    respond_with Enrollment.create(book_params)
  end

  def show
    respond_with @enrollment.to_json(
      :include => [
        { :student => {:only => :name} },
        { :course => { :only => :name } }
        ])

  end

  def update
    respond_with @enrollment.update(enrollment_params)
  end

  def destroy
    respond_with @enrollment.destroy
  end

  private
  def set_enrollment
    @enrollment = Enrollment.find(params[:id])
  end

  def enrollment_params
    params.require(:enrollment).permit(:name, :age)
  end
end

Example 5 - Creating your own API/app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController

 before_action :set_instructor, only: [:show, :update, :destroy]
  respond_to :json, :html

  def index
    @instructors = Instructor.all
    respond_with @instructors.to_json(
      :include => [
        { :students => {:only => :name} }
        ])
  end

  def create
    respond_with Instructor.create(book_params)
  end

  def show
    respond_with @instructor.to_json(
      :include => [
        {
          :students => {:only => :name}
        }
      ])
  end

  def update
    respond_with @instructor.update(instructor_params)
  end

  def destroy
    respond_with @instructor.destroy
  end

  private
  def set_instructor
    @instructor = Instructor.find(params[:id])
  end

  def instructor_params
    params.require(:instructor).permit(:name)
  end
end

Example 5 - Creating your own API/app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :set_student, only: [:show, :update, :destroy]
  respond_to :json, :html

  def index
      @student = Student.all
      # if request.format == 'json'
        respond_with @student.to_json(:include => { :instructor => { :only => :name } })
      # end
  end

  def create
    i = Instructor.find(params[:instructor_id])
    new_student = Student.create(student_params)
    i.students << new_student
    redirect_to '/students'
  end

  def new

    @student =  Student.new()
    @instructor_data = Instructor.all.map do |i|
       [i.name, i.id.to_i]

    end
    render :layout => false
  end

  def show
    # @instructor_name = @student.instructor.name
    # @student_hash = @student.attributes
    # @student_hash["instructor"] = @student.instructor.attributes
    # respond_with @student_hash
    respond_with @student.to_json(
      :include => {
        :instructor => {
          :only => :name
          }
        }
      )
    # respond_with student: @student, instructor_name: @instructor_name
  end

    def edit
    @student = Student.find(params[:id])
    @instructor_data = Instructor.all.map do |i|
       [i.name, i.id.to_i]
      end

    respond_with @student.to_json(
      :include => {
        :instructor => {
          :only => :name
          }
        }
      )
    # respond_with student: @student, instructor_name: @instructor_name
    end

  def update
  if request.format == 'json'
    respond_with @student.update_attributes(student_params)
  else
    @student.update_attributes(student_params)
    redirect_to '/students'
  end

  end

  def destroy
    @student = Student.find(params[:id])
    respond_with @student.destroy
  end

  private
  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :age, :instructor_id)
  end
end

Example 5 - Creating your own API/app/helpers/courses_helper.rb
module CoursesHelper
end

Example 5 - Creating your own API/app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

Example 5 - Creating your own API/app/helpers/instructors_helper.rb
module InstructorsHelper
end

Example 5 - Creating your own API/app/helpers/students_helper.rb
module StudentsHelper
end

Example 5 - Creating your own API/app/views/courses/delete.html.erb
<h1>Courses#delete</h1>
<p>Find me in app/views/courses/delete.html.erb</p>

Example 5 - Creating your own API/app/views/courses/edit.html.erb
<h1>Courses#edit</h1>
<p>Find me in app/views/courses/edit.html.erb</p>

Example 5 - Creating your own API/app/views/courses/new.html.erb
<h1>Courses#new</h1>
<p>Find me in app/views/courses/new.html.erb</p>

Example 5 - Creating your own API/app/views/courses/show.html.erb
<h1>Courses#show</h1>
<p>Find me in app/views/courses/show.html.erb</p>

Example 5 - Creating your own API/app/views/enrollments/create.html.erb
<h1>Enrollments#create</h1>
<p>Find me in app/views/enrollments/create.html.erb</p>

Example 5 - Creating your own API/app/views/enrollments/destroy.html.erb
<h1>Enrollments#destroy</h1>
<p>Find me in app/views/enrollments/destroy.html.erb</p>

Example 5 - Creating your own API/app/views/enrollments/index.html.erb
<h1>Enrollments#index</h1>
<p>Find me in app/views/enrollments/index.html.erb</p>

Example 5 - Creating your own API/app/views/enrollments/show.html.erb
<h1>Enrollments#show</h1>
<p>Find me in app/views/enrollments/show.html.erb</p>

Example 5 - Creating your own API/app/views/enrollments/update.html.erb
<h1>Enrollments#update</h1>
<p>Find me in app/views/enrollments/update.html.erb</p>

Example 5 - Creating your own API/app/views/students/_sharedform.html.erb
<%= form_for @student do |f| %>
	<p>
		<%= label_tag ("name") %>
		<%= f.text_field :name, id: "name" %>
	</p>
	<p>
		<%= label_tag ("age") %>
		<%= f.text_field :age, id: "age" %>
	</p>
	<p>
		<%= label_tag ("Instructor") %>
		<%= select_tag(:instructor_id, options_for_select(@instructor_data, params[:id]),
		:id => 'instructor') %>
	</p>
	<p>
		<%= submit_tag("Submit") %>
	</p>
<% end %>

Example 5 - Creating your own API/app/views/students/delete.html.erb
<h1>Students#delete</h1>
<p>Find me in app/views/students/delete.html.erb</p>

Example 5 - Creating your own API/app/views/students/edit.html.erb
<%= form_for @student do |f| %>
	<p>
		<%= label_tag ("name") %>
		<%= f.text_field :name, id: "name" %>
	</p>
	<p>
		<%= label_tag ("age") %>
		<%= f.text_field :age, id: "age" %>
	</p>
	<p>
		<%= label_tag ("Instructor") %>
		<%= select_tag(:instructor_id, options_for_select(@instructor_data, params[:id]),
		:id => 'instructor') %>
	</p>
	<p>
		<%= submit_tag("Submit") %>
	</p>
<% end %>

Example 5 - Creating your own API/app/views/students/index.html.erb
<h1>Student List</h1>

<% @student.each do |student| %>
	<p>
		Name: <%= student.name %>,
		Age: <%= student.age %>
	</p>

	<p>
		<%= link_to 'Show', student_path(student) %> |
		<%= link_to 'Edit', edit_student_path(student), id: "update" %> |
		<%= link_to "Delete", student, method: :delete, data: {:confirm =>"You sure you want to do that?"} %>
	</p>

<% end  %>

<%= link_to 'New', new_student_path, id: "new" %>

<%= link_to 'Hide form', new_student_path, id: "hideForm" %>

<div class="newform">


</div>

Example 5 - Creating your own API/app/views/students/new.html.erb
<%= form_for @student do |f| %>
	<p>
		<%= label_tag ("name") %>
		<%= f.text_field :name, id: "name" %>
	</p>
	<p>
		<%= label_tag ("age") %>
		<%= f.text_field :age, id: "age" %>
	</p>
	<p>
		<%= label_tag ("Instructor") %>
		<%= select_tag(:instructor_id, options_for_select(@instructor_data, params[:id]),
		:id => 'instructor') %>
	</p>
	<p>
		<%= submit_tag("Submit") %>
	</p>
<% end %>

Example 5 - Creating your own API/app/views/students/show.html.erb
<p> Name:
	<%= @student.name %>
</p>

<p> Age:
	<%= @student.age %>
</p>

<%= link_to 'Show all', students_path %>