Example 4 - Server side OMDB/serveromdb/config/routes.rb
Rails.application.routes.draw do

	get 'info/results', to: 'info#results'
  post 'info/results', to: 'info#add'
  resources :favorites

  resources :info
  root 'info#index'

end

Example 4 - Server side OMDB/serveromdb/app/models/favorite.rb
class Favorite < ActiveRecord::Base
end

Example 4 - Server side OMDB/serveromdb/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
  	@favorites = Favorite.all
  end

  def create
  	Favorite.create(name: params[:title])
  	redirect_to '/favorites'
  end

  def edit
  end
end

Example 4 - Server side OMDB/serveromdb/app/controllers/info_controller.rb
class InfoController < ApplicationController
  def index
  end

  def results
    @query = params[:query]

    request = Typhoeus.get(
      "http://www.omdbapi.com",
      :params => {:s => @query}
      )

		@results = JSON.parse(request.body)

    puts @results

  end

    def show
      @favorite = Favorite.new()
    @movie = params[:id]
    puts "THIS IS PARAMS!"
    puts @movie

    request = Typhoeus.get(
      "http://www.omdbapi.com",
      :params => {:i => @movie}
      )
    @movie_result = JSON.parse(request.body)
    puts @movie_result
    end

    def add
      redirect_to index
    end
end

Example 4 - Server side OMDB/serveromdb/app/helpers/favorites_helper.rb
module FavoritesHelper
end

Example 4 - Server side OMDB/serveromdb/app/helpers/info_helper.rb
module InfoHelper
end

Example 4 - Server side OMDB/serveromdb/app/views/favorites/edit.html.erb
<h1>Favorites#edit</h1>
<p>Find me in app/views/favorites/edit.html.erb</p>

Example 4 - Server side OMDB/serveromdb/app/views/favorites/index.html.erb
<% @favorites.each	do |favorite| %>
	<p>
		<%= favorite.name %>
	</p>
<% end %>

<%=  link_to ("Search again"), info_index_path %>

Example 4 - Server side OMDB/serveromdb/app/views/favorites/show.html.erb
<h1>Favorites#show</h1>
<p>Find me in app/views/favorites/show.html.erb</p>

Example 4 - Server side OMDB/serveromdb/app/views/info/index.html.erb
<form action="info/results">
	<p>
		<label for="movie">Movie:</label>
		<input type="text" name="query" id="movie">
	</p>
	<p>
		<input type="submit" value="Search">
	</p>
</form>

<%= link_to ("See my favorites"), (favorites_path) %>

Example 4 - Server side OMDB/serveromdb/app/views/info/results.html.erb
    <% if @results["Search"] == nil %>
      <li class="result">That movie title doesn't exist!</li>
    <%else%>
      <% @results["Search"].each do |x| %>
        <p>

        	 <a id="a_results" href="http://localhost:3000/info/<%=x["imdbID"]%>"><%= x["Title"] %></a>
        </p>
        <p>
        	<%= x["Year"] %>
        </p>




      <% end %>
    <%end%>

Example 4 - Server side OMDB/serveromdb/app/views/info/show.html.erb
<p>
	Title: <%= @movie_result["Title"] %>
</p>
<p>
	Year: <%= @movie_result["Year"] %>
</p>
<p>
	Plot: <%= @movie_result["Plot"] %>
</p>
<p>
	<%= link_to "Search Again", (info_index_path) %>
</p>
<p>

	<%= form_tag @favorite do |f|  %>
	<%= text_field_tag "title", @movie_result["Title"] %>
	<%= submit_tag "Add to Favorites"%>


	<% end %>





</p>

Example 4 - Server side OMDB/serveromdb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Serveromdb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>